config/routes.rb
Rails.application.routes.draw do
  get 'onboard/initialize'

  get 'welcome/index'

  get 'welcome/zillow'

  get 'welcome/trulia'

  get 'welcome/listglobally'

  get 'welcome/blackknight'

  get 'welcome/propertyvalue'

  get 'welcome/mediansales'

  get 'welcome/propertyinformationreport'

  get 'welcome/comparablesales'

  get 'welcome/neighborhoodv'

  get 'welcome/annualpercentage'

  get 'welcome/unitsales'

  get 'welcome/salesbyrange'

  get 'welcome/forclosures'

  get 'welcome/hoodlinetest'

  get 'welcome/marketreports'

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/onboard.rb
class Onboard < ApplicationRecord
	

end

app/models/onboarddatum.rb
class Onboarddatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/onboard_controller.rb
class OnboardController < ApplicationController
  def initialize
	@onboard = Onboard.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
    require 'net/http'
    require 'uri'
    require 'json'
    require 'httparty'
   

  def index
  end

  def zillow
  end

  def trulia
  end

  def listglobally
  end

  def blackknight
  end
  
  def propertyvalue
  end

  def mediansales
  end

  def propertyinformationreport
  end

  def comparablesales
  end

  def neighborhoodv  
  end

  def annualpercentage
  end

  def unitsales
  end

  def salesbyrange
  end

  def forclosures

  end

  def marketreports
    headers = {
      "APIKEY" => "219fcf892e07493cfc5246f9f7e66ba2",
      "Accept" => "application/json"
    }
  @response = HTTParty.get("https://search.onboard-apis.com/communityapi/v2.0.0/Area/Full/?AreaId=CO44003", :headers => headers)
 
  JSON.parse(@response.body)


  end



end

app/helpers/application_helper.rb
module ApplicationHelper

	def is_active?(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/onboard_helper.rb
module OnboardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APR Property Data</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="<%is_active?(welcome_index_path) %> nav-item">
              <a class="nav-link "><%= link_to "Home", welcome_index_path %> <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link"><%= link_to "Zillow Reports", welcome_zillow_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link"><%= link_to "Trulia Reports", welcome_trulia_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link"><%= link_to "ListGlobally Reports", welcome_listglobally_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link"><%= link_to "Black Knight Financial Reports", welcome_blackknight_path %></a>
            </li>
          </ul>
        </nav>
        <center><h1>APR Property Data Application</h1></center>
      </div>
  	
    <%= yield %>
    </div>
  </body>
</html>

app/views/onboard/initialize.html.erb
<h1>Onboard#initialize</h1>
<p>Find me in app/views/onboard/initialize.html.erb</p>

app/views/welcome/blackknight.html.erb
<h3>Black Knight Reporting Tools</h3>
<br>
<h4> Please select from the list of available Reports below.</h4>
<br>
<div>
<p> 
	<ul>
		<li class="nav-item">
            <a class="nav-link"><%= link_to "Property Value Report", welcome_propertyvalue_path %></a>
        </li>
        <li class="nav-item">
            <a class="nav-link"><%= link_to "Median Sales Report", welcome_mediansales_path %></a>
        </li>
         <li class="nav-item">
            <a class="nav-link"><%= link_to "Comparable Sales Report", welcome_comparablesales_path %></a>
        </li>
         <li class="nav-item">
            <a class="nav-link"><%= link_to "Sales by Price Range Report", welcome_salesbyrange_path %></a>
        </li>
         <li class="nav-item">
            <a class="nav-link"><%= link_to "Neighborhood Valuation by ZIP", welcome_neighborhoodv_path %></a>
        </li>
         <li class="nav-item">
            <a class="nav-link"><%= link_to "Neighborhood Annual Percentage Change in Valuation by ZIP", welcome_annualpercentage_path %></a>
        </li>
         <li class="nav-item">
            <a class="nav-link"><%= link_to "Unit Sales Volume by ZIP", welcome_unitsales_path %></a>
        </li>
         <li class="nav-item">
            <a class="nav-link"><%= link_to "Active Forclosure by ZIP", welcome_forclosures_path %></a>
        </li>

	</ul>

</p>
</div>

app/views/welcome/comparablesales.html.erb
<html>
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch4(type);
 }


 function SubmitSearch4(type) {
 if (document.getElementById("txtAddress4") != null) {
 var Address = document.getElementById('txtAddress4').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "8";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "8";
 }

 GetLPSWidget4(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget4(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived4(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived4(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML4).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML4').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table>
 	<tr>
 		<td><h3>Comparable Sales by ZIP</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter a ZIP code and click 'Submit' to view a comparable sales report. </p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress4" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch4()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML4">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 

app/views/welcome/forclosures.html.erb
<html>
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch8(type);
 }


 function SubmitSearch8(type) {
 if (document.getElementById("txtAddress8") != null) {
 var Address = document.getElementById('txtAddress8').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "2";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "2";
 }

 GetLPSWidget8(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget8(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived8(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived8(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML8).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML8').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table>
 	<tr>
 		<td><h3>Active Forclosure by ZIP</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter a ZIP code and click 'Submit' to view an active forclosures report. </p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress8" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch8()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML8">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 

app/views/welcome/hoodlinetest.html.erb
<div class="hoodkit-neighborhood-embed" data-neighborhood="alamo-square" data-theme="carbon"></div>
<script src="https://e651c2178b92d3674869a0aea25bd527.kit.hoodline.com:/api.js"></script>

app/views/welcome/index.html.erb
<div>
<center><h3>Data for Syndicated Properties</h3></center>
<br>
<div class="jumbotron">
        
        <p class="lead">Here you can view daily, up-to date information about a property's presence on Zillow and/or Trulia. Information like the number of views it has received, leads generated, impressions, etc is available at the links in the navigation area. <p> Please use the <b>'CTRL-F'</b> or <b>'CMD-F'</b> feature to search the page for the property you need data on. If a property isn't present here, it is not being syndicated to Zillow / Trulia. Generally, using the MLS ID is the best way to find a property.</p> <p>This data is updated once daily, when reporting is received from our data partners.</p><p> For questions or legacy data, please email the software administrator Christopher Bradford at cbradford@apr.com</p>
      </div>

</div>

app/views/welcome/mediansales.html.erb
<html>
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch2(type);
 }


 function SubmitSearch2(type) {
 if (document.getElementById("txtAddress2") != null) {
 var Address = document.getElementById('txtAddress2').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "4";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "4";
 }

 GetLPSWidget2(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget2(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived2(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived2(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML2).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML2').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table>
 	<tr>
 		<td><h3>Property Median Sales by Zip</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter a Zip Code and click 'Submit' to see data about Median Sales for that Zip Code.</p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress2" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch2()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML2">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 

app/views/welcome/neighborhoodv.html.erb
<html>
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch5(type);
 }


 function SubmitSearch5(type) {
 if (document.getElementById("txtAddress5") != null) {
 var Address = document.getElementById('txtAddress5').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "2048";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "2048";
 }

 GetLPSWidget5(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget5(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived5(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived5(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML5).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML5').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table>
 	<tr>
 		<td><h3>Neighborhood Valuation by ZIP</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter a ZIP code and click 'Submit' to view a neighborhood valuation report. </p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress5" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch5()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML5">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 

app/views/welcome/propertyinformationreport.html.erb
<html>
<!-- this report returns null, update if BKFS fixes --> 
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch3(type);
 }


 function SubmitSearch3(type) {
 if (document.getElementById("txtAddress3") != null) {
 var Address = document.getElementById('txtAddress3').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "524288";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "524288";
 }

 GetLPSWidget3(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget3(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived3(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived3(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML3).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML3').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table> 
 	<tr>
 		<td><h3>Property Information Report</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please an address and click 'Submit' to view an extensive property information report. </p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress3" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch3()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML3">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 

app/views/welcome/propertyvalue.html.erb
<html>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch(type);
 }


 function SubmitSearch(type) {
 if (document.getElementById("txtAddress") != null) {
 var Address = document.getElementById('txtAddress').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "1";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "1";
 }

 GetLPSWidget(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
 <table>
 	<tr>
 		<td><h3>Property Value Search</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter the address of a given property and click 'Submit' to see data about its current value on the market.</p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
 </body>
 </html>

app/views/welcome/salesbyrange.html.erb
<html>

<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch9(type);
 }


 function SubmitSearch9(type) {
 if (document.getElementById("txtAddress9") != null) {
 var Address = document.getElementById('txtAddress9').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "524288";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "524288";
 }

 GetLPSWidget9(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget9(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived9(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived9(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML9).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML9').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table>
 	<tr>
 		<td><h3>Home Sales by Price Range</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter a ZIP code and click 'Submit' to view a home sales by price range report. </p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress9" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch9()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML9">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 

app/views/welcome/unitsales.html.erb
<html>
<script src="https://v2.sitexdata.com/Graph/js/lpstoolkit.js" type="text/javascript"></script>
<link href="https://xml.sitexdata.com/restapi/Assets/css/chart.css"
rel="stylesheet"type="text/css" />
<script language="javascript" type="text/javascript">
 //<![CDATA[ //Required for calling the Period Code (Month,Bi-Monthly,Quaterly)
 this.GetLPSChart = function(type) {
 // 1= Monthly
 // 2= Bi-Monthly
 // 3= Quarterly

 SubmitSearch7(type);
 }


 function SubmitSearch7(type) {
 if (document.getElementById("txtAddress7") != null) {
 var Address = document.getElementById('txtAddress7').value;
 var AuthKey = "16D8B43C-897E-441F-B771-D7C5D18D8FD1_1";
 var RequestType = "256";
 //Set the requestType
 if (type != undefined) {
 RequestType = RequestType + "_" + type;
 }
 else {
 type = "256";
 }

 GetLPSWidget7(Address, RequestType, AuthKey, type);
 }
 }
 function GetLPSWidget7(Address, RequestType, AuthKey, type) {
 var _request = new LPS().Request(AuthKey, Address, RequestType, "Result");
 this.Result = function(result) {
 onDataReceived7(result, type);
 _request.Dispose();
 }
 }
 function onDataReceived7(result, type)
{
 if (result.Status == "ERROR") {
 document.getElementById(divHTML7).innerHTML = result.Message;

 } else { 
 	document.getElementById('divHTML7').innerHTML =
	result.DataCollections[0].Visualization;
 	//Required for display the Chart.
	var chart = new LPSChart();
 	chart.chartSetup();
 	chart.ChartSelected(type);
 }
 }
 //]]>
</script>
<body>
<table>
 	<tr>
 		<td><h3>Unit Sales Volume by ZIP</h3>
 		</td>
 	</tr>
 	<tr> 
 	<td> <p>Please enter a ZIP code and click 'Submit' to view a unit sales volume by ZIP report. </p>
 	</td>
 	</tr>
 	<tr>
 		<td>
 		<input type="text" style="width: 250px;" id="txtAddress7" />
 		</td>
 		</tr>
 	
 		<td>
 		<br> <input type="button" class="btn btn-primary" onclick="SubmitSearch7()" value="Submit" />
 		</td>
 	</tr>
 	<tr>
 		<td>
 		&nbsp;
 		</td>
 	</tr>
 	<tr>
 		<td colspan="2">
 			<div id="divHTML7">
 			</div>
 		</td>
 	</tr>
 </table>
 <p> <a class="nav-link"><%= link_to "Return to Black Knight Financial Reports page", welcome_blackknight_path %></a></p>
</body>
</html> 